### ISSUE TITLE
Review from DataWaves

### ISSUE THREAD

**Issue by Saharsh-Bhave** [INFO-526-FA24/project-2-visual-voyagers#11]
### 1. What is the good thing in the poster?
The team has chosen a very interesting topic for analysis. They have also done a good job drawing inferences from their dataset and their visualizations.

 ### 2. What do you think can/should be improved?
The heatmap/correlation matrix is very large in size. They might benefit from reducing it in size as having a larger size is increasing their visualization's data to ink ratio.

**Comment by virensasalu** [comment]
The correlation matrix is now optimized. We have improved on it. 
Thank you!
