### ISSUE TITLE
review from the team DreamJobs

### ISSUE THREAD

**Issue by Lucifer970901** [INFO-526-FA24/project-2-visual-voyagers#12]
overall looks good and interesting, Use contrasting colors (e.g., red, blue, green, purple) for each model's AUC curve.
Avoid overlapping shades by leveraging colorblind-friendly palettes like Viridis or ColorBrewer to ensure accessibility. and add zoom in picture details so that the variation is visible.

**Comment by virensasalu** [comment]
Yes, added the zoom 
Thank you
