### ISSUE TITLE
Review from team Data Nexus

### ISSUE THREAD

**Issue by SiddheshwarSinghNegi** [INFO-526-FA24/project-2-visual-voyagers#13]
Strengths: The project features a well-organized layout that ensures clarity and makes it easy to navigate. The choice of colors is visually appealing and complements the overall design, contributing to an engaging presentation.

Weaknesses: The heatmap appears overly complex, which might make it difficult for the audience to interpret the data effectively

**Comment by virensasalu** [comment]
Yes, I agree. we have improved upon it and fixed the heat map. Now the interpretatention of the plot is improved. 
Than you.
