### ISSUE TITLE
Review from DataVizionaries

### ISSUE THREAD

**Issue by srikrish2812** [INFO-526-FA24/project-2-visual-voyagers#14]
**Topic:** Breast Cancer Detection

**Strength:** The visualizations are simple and self-explanatory. Classical models like SVM, Logistic Regression and Naive Bayes were compared in a detailed way with good visualizations.

**Weakness:** Instead of plotting the correlation matrix for all variables, you can choose a few important variables and plot the correlation heatmap. This makes it easy for the viewers to understand the dependency between factors/variables.

**Comment by virensasalu** [comment]
Instead of plotting the correlation matrix for all variables, you can choose a few important variables and plot the correlation heatmap. This makes it easy for the viewers to understand the dependency between factors/variables.
- We have actually done that. We will emphasize more on it thank you.
