### ISSUE TITLE
Peer Review by Team Insight Decoders

### ISSUE THREAD

**Issue by hemabk** [INFO-526-FA24/project-2-visual-voyagers#15]
Hello Team Visual Voyagers,

Strengths:
1) Effectively utilized the ROC-AUC curve to evaluate performance against specificity and sensitivity.
2) The analysis demonstrates a strong understanding of evaluation metrics for classification tasks.

Weaknesses:
1) The alignment of elements in the corner appears uneven, affecting the poster's visual balance.
2) Some design aspects could be refined for a more polished presentation.

**Comment by virensasalu** [comment]
- Yes, we have corrected the alignment
- Thank you for your advice.
