### ISSUE TITLE
Peer Review by InfoCrew

### ISSUE THREAD

**Issue by tallapaneniv** [INFO-526-FA24/project-2-visual-voyagers#16]
Strength - All visualizations looked good everything was explained well,  if not all colors most went well together. The color pallet for the visualizations worked very well. 

Weakness - The poster looked A very cluttered with all the visulizations and information squished together, poster could be more neat with better spacing and organization.

**Comment by virensasalu** [comment]
Hi, we have reduced the sizes of the graphs and restructured the whole poster!Thank you.
