### ISSUE TITLE
Peer Review - 4X4

### ISSUE THREAD

**Issue by jaelynkapuaioane** [INFO-526-FA24/project-2-visual-voyagers#4]
1. Kapua Ioane - jaelynkapuaioane
   Tanmay Naik - tanmaynaik11
   Krisha Vardhni Mahesh - KrishaVM 
   Nikhil Badgujar - bnikhil

2. The goal of the project is to visualize different Machine Learning Classification Algorithms to help determine if a tumor is malignant or benign.

3. The data used is the Breast Cancer Diagnostic Data from UCI Machine Learning Repository. The data has 569 samples with 30 features describing tumor characteristics that determine binary classification of benign or malignant 

4. There are four research questions - 
- How does the accuracy of Model A (e.g., Logistic Regression) compare to Model B (e.g., SVM) when predicting the diagnosis? Which model performs best on the test set?
-How do the Receiver Operating Characteristic (ROC) curves and Area Under the Curve (AUC) scores differ among the models?
-How does tuning specific hyperparameters (e.g., regularization in Logistic Regression, kernel type in SVM) affect model performance?
-How robust the models is to noise and outliers?

The methods to answer each question is unclear.

5. How will each of the questions be answered? What specifically are you visualizing?  

6. Describing what is being visualized and having a clear idea of that goal will make your project stronger.

7. This has really important medical usage. Being able to successfully and confidently identify the risk of a tumor can save lives. Talking about that usage can make your project more engaging.

8. Repo Structure Not Provided within Proposal

9. It seems like you have 1 question per person - this can make your project seem a little disconnected. Make sure to work with groupmates to have a cohesive story within the project. In addition, there doesn't seem to be anything related to visualization within the project, rather, it's a Machine Learning Project.

**Comment by annahoju** [comment]
Team Visual Voyagers - how are you or are you addressing team 4x4's team peer review.

**Comment by gr98765** [comment]
We've already addressed all the issues and integrated suggestions by making necessary changes in our proposal. We're moving forward by closing this issue again and appreciate the team's insightful peer review and contribution.

**Comment by annahoju** [comment]
Just so I understand, the issues that team 4x4 bring up were addressed by the first peer review and you addressed them there?

**Comment by gr98765** [comment]
Apologies for the oversight; the issues raised by Team 4x4 were already considered during the first peer review and addressed in the revised proposal, but we didn't explicitly comment on it while closing the issue.
