### ISSUE TITLE
Instructor review 

### ISSUE THREAD

**Issue by annahoju** [INFO-526-FA24/project-2-visual-voyagers#6]
Hello team Visual Voyagers - 

I have reviewed your proposal. It is an interesting project that appears to be set up for success. Your appraoches to analysis and visualization should be able to answer the questions proposed. 

One area of consideration that I do not see is addressed int he proposal is the approach to the poster presentation. As a team, spend some time storyboarding the poster and consider how such an ambitious project will be translated into a poster.  

|          | Available | Earned |
|----------|-----------|--------|
| Data     | 3         |    3    |
| Proposal | 5         |   5     |
| Workflow | 1         |    1    |
| Teamwork | 1         |     1   |
| Total    | 10        |   10     |

**Comment by virensasalu** [comment]
Hi Anna, 
We have addressed all the issue and we are woking on story boarding. 
Thank you,
Visual Voyagers
