### ISSUE TITLE
Poster review MOCK ishowcase

### ISSUE THREAD

**Issue by annahoju** [INFO-526-FA24/project-2-visual-voyagers#7]
Suggestion - remove the half of the triangle in the correlogram. 
I like the color choice and the label placement

Zooming in on the arc for figure 2 would be helpful.

**Comment by virensasalu** [comment]
Hi Anna, 
All the suggestions have been addressed. We have zoomed in on the arc (Auc and Roc curve)
In addition, we have implemented simpler heatmap for more understandability. 
Thank you,
Visual Voyagers
