### ISSUE TITLE
Review from Team Stat_Squad

### ISSUE THREAD

**Issue by durgagubbala86** [INFO-526-FA24/project-2-visual-voyagers#9]
Strength:
Clear model comparison with excellent typography and label placement.

Weakness:
Differentiate scatterplots with distinct colors and zoom in on Figure 2's arc; remove half triangle in the correlogram.

Suggestion:
Storyboard the poster for a more effective presentation.

**Comment by virensasalu** [comment]
All the changes have been addressed. Thank you!
